import { readStyles } from "./style-fixture.mjs";
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('侧栏按六个工作区组织并自动展开当前工作区', () => {
  const html = fs.readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
  const main = fs.readFileSync(new URL('../public/src/main.js', import.meta.url), 'utf8');
  const publication = fs.readFileSync(new URL('../public/src/views/publication.js', import.meta.url), 'utf8');
  const styles = readStyles();
  const editorCss = fs.readFileSync(new URL('../public/assets/styles/editor.css', import.meta.url), 'utf8');
  for (const label of ['今日工作', '采集', '文章生产', '图文生产', '发布', '资产']) {
    assert.match(html, new RegExp(label));
  }
  assert.equal((html.match(/class="nav-group"/g) || []).length, 6);
  assert.equal((html.match(/class="nav-item/g) || []).length, 25);
  assert.match(html, /data-view="material-inbox"[^>]*>[\s\S]*?nav-label">素材入箱/);
  assert.match(html, /data-view="wechat-review-prep"[^>]*>[\s\S]*?nav-label">复盘数据台/);
  assert.match(html, /data-view="wechat-review"[^>]*>[\s\S]*?nav-label">公众号复盘/);
  assert.match(html, /data-view="content-feedback"[^>]*>[\s\S]*?nav-label">内容反哺/);
  assert.match(main, /"content-feedback": "\.\/views\/content-feedback\.js"/);
  assert.doesNotMatch(html, /class="wechat-review-flow/);
  assert.match(html, /data-view="artifacts"[^>]*>[\s\S]*?nav-label">产物中心/);
  assert.match(html, /data-view="publication"[^>]*>[\s\S]*?nav-label">发布中心/);
  assert.match(html, /data-view="wechat-review"[^>]*>[\s\S]*?nav-label">公众号复盘/);
  assert.match(html, /id="quick-material-button">＋ 快速记素材/);
  assert.match(html, /id="quick-material-dialog"/);
  assert.match(html, /data-publication-filter="pending"[^>]*>未发布/);
  assert.doesNotMatch(html, /data-publication-filter="published"/);
  assert.match(publication, /if \(item\.metric_match_count\) return \{ id: "reviewed", label: "已复盘" \};[\s\S]*return \{ id: "pending", label: "未发布" \};/);
  assert.match(publication, /publicationFilter === "social"[\s\S]*item\.artifact_type === "图文发布文案"/);
  assert.match(publication, /早报终稿/);
  assert.doesNotMatch(publication, /id: "published"/);
  assert.match(main, /bindQuickMaterialCapture/);
  assert.ok(html.indexOf('data-view="publication"') < html.indexOf('data-view="artifacts"'));
  assert.ok(html.indexOf('data-view="material-inbox"') < html.indexOf('data-view="skills"'));
  assert.ok(html.indexOf('data-view="wechat-review"') < html.indexOf('data-view="skills"'));
  assert.ok(html.indexOf('data-view="wechat-review-prep"') < html.indexOf('data-view="wechat-review"'));
  assert.match(html, /id="view-wechat-review-prep"/);
  assert.match(html, /id="wechat-prep-import-file"/);
  assert.match(html, /data-wechat-review-mode="article"/);
  assert.match(html, /data-wechat-review-mode="social"/);
  assert.doesNotMatch(html, /class="wechat-review-secondary"/);
  assert.match(html, /class="wechat-review-analysis-grid"/);
  assert.match(html, /id="content-strategy-panel"/);
  assert.match(html, /选题 · 标题 · 正文/);
  assert.doesNotMatch(html, /content-feedback-targets/);
  const feedback = fs.readFileSync(new URL('../public/src/views/content-feedback.js', import.meta.url), 'utf8');
  assert.match(feedback, /作为 AI 调整账号策略与技能文件的参考/);
  assert.doesNotMatch(feedback, /renderTargets|content-feedback-targets/);
  assert.doesNotMatch(feedback, /data-feedback-handoff-target/);
  assert.doesNotMatch(fs.readFileSync(new URL('../public/src/views/editor.js', import.meta.url), 'utf8'), /takeFeedbackHandoff/);
  assert.match(html,/data-view="topics"[^>]*>[\s\S]*?nav-label">文章选题池/);
  assert.match(html,/data-view="editorial"[^>]*>[\s\S]*?nav-label">热点事件/);
  assert.doesNotMatch(html, /data-view="models">模型运行/);
  assert.match(html, /class="rail-utility-group" aria-label="扩展与定制"/);
  for (const view of ['skills', 'themes', 'system']) assert.match(html, new RegExp(`class="nav-utility" data-view="${view}"`));
  assert.ok(html.indexOf('data-view="skills"') < html.indexOf('data-view="themes"'));
  assert.match(main, /group\.open = Boolean\(activeNavItem && group\.contains\(activeNavItem\)\)/);
  assert.match(main, /setAttribute\("aria-current", "page"\)/);
  assert.match(main, /\.nav-item\.active,\.nav-utility\.active/);
  assert.match(styles, /\.nav-group>summary/);
  assert.match(styles, /\.content-feedback-metrics\{[^}]*grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/);
  assert.match(editorCss, /\.content-feedback-metrics\{[^}]*grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/);
  assert.match(styles, /\.rail nav \{ flex:none;max-height:240px/);
  assert.ok(html.indexOf('data-view="system"') > html.indexOf('class="rail-utility-group"'));
  assert.match(styles,/nav \{ flex:1;min-height:0/);
});

test('运行配置页区分服务状态、环境参数与本地恢复', () => {
  const html = fs.readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
  const main = fs.readFileSync(new URL('../public/src/main.js', import.meta.url), 'utf8');
  const system = fs.readFileSync(new URL('../public/src/views/system.js', import.meta.url), 'utf8');
  assert.match(html, /class="runtime-commandbar"/);
  assert.match(html, /class="system-workspace"/);
  assert.match(html, /class="maintenance-panel"/);
  assert.doesNotMatch(html, /control-card backup-card/);
  assert.match(main, /system: "运行与配置中心"/);
  assert.doesNotMatch(html,/configuration-console-strip/);
  assert.doesNotMatch(html,/data-config-panel="app"/);
  assert.match(html,/id="config-panel-extensions"/);
  assert.doesNotMatch(html,/data-config-panel="rsshub"/);
  assert.doesNotMatch(system,/selectConfigTab\("extensions"\)/);
});
